### ISSUE TITLE
Проблема с локализацией

### ISSUE THREAD

**Issue by AkakievMD** [zabbix/community-templates#1]
Locale for language "en_US" is not found on the web server. Tried to set: en_US, en_US.utf8, en_US.UTF-8, en_US.iso885915, en_US.ISO8859-1, en_US.ISO8859-2, en_US.ISO8859-4, en_US.ISO8859-5, en_US.ISO8859-15, en_US.ISO8859-13, en_US.CP1131, en_US.CP1251, en_US.CP1251, en_US.CP949, en_US.KOI8-U, en_US.US-ASCII, en_US.eucKR, en_US.eucJP, en_US.SJIS, en_US.GB18030, en_US.GB2312, en_US.GBK, en_US.eucCN, en_US.Big5HKSCS, en_US.Big5, en_US.armscii8, en_US.cp1251, en_US.eucjp, en_US.euckr, en_US.euctw, en_US.gb18030, en_US.gbk, en_US.koi8r, en_US.tcvn. Unable to translate Zabbix interface.
![image](https://user-images.githubusercontent.com/80063467/143460970-77e9a0be-6f7e-49b3-8c1c-91c3448433fc.png)
![image](https://user-images.githubusercontent.com/80063467/143460919-bad23d79-b730-4eea-8677-6f79e716fcf2.png)

**Comment by daftu** [comment]
This is not template related question. Please ask it on Zabbix community forums.
