### ISSUE TITLE
RDP template zabbix 6.0.6 "Unable to parse at line 8 (near "<!DOCTYPE html>")."

### ISSUE THREAD

**Issue by Swinrus** [zabbix/community-templates#111]
Hello!
On Zabbix 6.0.6 when I try to import this template, I have a error "Unable to parse at line 8 (near "")."
Is there a solution for this problem?

**Comment by cklabautermann** [comment]
Hi,
I have exactly the same issue with the https://github.com/zabbix/community-templates/tree/main/Network_Devices/Cisco/template_lacp_ports_monitoring template.
Using Zabbix 6.0.6.
Thanks
