### ISSUE TITLE
Template for HP ProLiant DL360 Gen10 (ilo 5) snmp3, zabbix 6.0

### ISSUE THREAD

**Issue by Swinrus** [zabbix/community-templates#118]
Hi all!
Please help find a working template for snmpv3 ilo 5 for zabbix 6.0.
I manage to collect information on snmp2, but the task is to use encryption.

**Comment by igorbach** [comment]
Hello!
Please try official out-of-the-box Zabbix  templates
https://www.zabbix.com/integrations/hpe
