### ISSUE TITLE
Need zabbix agent for legacy HPUX 11.11 

### ISSUE THREAD

**Issue by securewithsam** [zabbix/community-templates#124]
Unable to install zabbix agent for legacy HPUX 11.11 , read manual link is broken .
Can you pls provide with instructions ?

https://www.zabbix.com/download_agents?version=1.8&release=1.8.2&os=HPUX&os_version=11.11&hardware=pa_risc&encryption=No+encryption&packaging=Archive&show_legacy=1

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope. You may to get some assistance on [Zabbix forum](https://www.zabbix.com/forum) or [Zabbix international community in Telegram](https://t.me/ZabbixTech)
