### ISSUE TITLE
template_monitor_one_linux_service_using_systemctl

### ISSUE THREAD

**Issue by maneshmohanan1** [zabbix/community-templates#128]
Hi Zabbix community
Here I am using this template to monitor the service but am facing this issue "This type of information may not match the key."

 needs your help on this 

https://github.com/zabbix/community-templates/blob/main/Operating_Systems/Linux/template_monitor_one_linux_service_using_systemctl/6.0/template_monitor_one_linux_service_using_systemctl.yaml

![image](https://user-images.githubusercontent.com/68895389/183018122-4c0fa18d-33e3-4468-814f-c9db21aee569.png)
![image](https://user-images.githubusercontent.com/68895389/183018388-9f441cba-f592-494a-8a80-2da097c579d9.png)

**Comment by cmmata** [comment]
I am not sure, but can it be that the `system.run` execution returns a string and not a numeric type like you are configuring? Change `type of information` to string and check if it works.

**Comment by maneshmohanan1** [comment]
Thanks its working now
