### ISSUE TITLE
template_module_windows_users.yaml não me traz conexoes RemoteAPP

### ISSUE THREAD

**Issue by 18vamberto** [zabbix/community-templates#147]
Bom dia.

Tenho um ambiente em nuvem onde os usuários acessam aplicação através  de um virtualizado, essas conexões são remoteapp, porem o template não me traz esse numero de usuários conectados em meus servidores.

Pode me dar uma ajuda?

Atenciosamente.

**Comment by igorbach** [comment]
Hello!
Zabbix community templates project is internationalone, please, use English when you're creating new issues
