### ISSUE TITLE
downlaod Arcserve_UDP_VMCount.ps1

### ISSUE THREAD

**Issue by jacneto1** [zabbix/community-templates#159]
where can i download the Arcserve_UDP_VMCount.ps1 file?

**Comment by V-Vesely** [comment]
I would like to join to this question - I dont know where can I find this script - I hoped that it will be included in Arcerve server or client but I didnt find it ...
Thank you for tip

**Comment by mgoegel** [comment]
Me too...

**Comment by RPWimmer** [comment]
https://github.com/RPWimmer/zabbix-templates-arcserve-udp
