### ISSUE TITLE
Json Path not working

### ISSUE THREAD

**Issue by jesulo** [zabbix/community-templates#16]
Json Path not working, give error in Test all steps but individual test not problem.
cannot extract value from json by path "$.lastName": cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'John'
for the second parameter for prossecing
but Json format is okay

{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}

**Comment by colttt** [comment]
in which tempalte?

**Comment by mtxadmin** [comment]
Structure seems to be AD-like.
