### ISSUE TITLE
template_huawei_oceanstore/5.4/huawei_get_state.py

### ISSUE THREAD

**Issue by SD3vEng** [zabbix/community-templates#21]
[Good afternoon! Could you add to the repository huawei_get_state.py the script, otherwise it is missing 
https://github.com/zabbix/community-templates/tree/main/Storage_Devices/Huawei/template_huawei_oceanstore/5.4

**Comment by oscar120584** [comment]
Thanks for the feedback. The [script ](https://github.com/zabbix/community-templates/tree/main/Storage_Devices/Huawei/template_huawei_oceanstore/5.4/files)is restored.

**Comment by SD3vEng** [comment]
Просто этому скрипту 2года и не известно рабочий он или нет. Проблема при запуске что он ругается на device_id

**Comment by oscar120584** [comment]
> 

Да, это он. [Страничка ](https://share.zabbix.com/storage-devices/huawei/huawei-oceanstore)пока доступна. 
[Судя по всему](https://github.com/aklyuk/zabbix-huawei-storages/issues/5), автор шаблона его не поддерживает.

**Comment by proffust** [comment]
> Просто этому скрипту 2года и не известно рабочий он или нет. Проблема при запуске что он ругается на device_id

скрипт поддерживается и используется у нас в инфраструктуре

**Comment by proffust** [comment]
учётка локальная или доменная? 

> Просто этому скрипту 2года и не известно рабочий он или нет. Проблема при запуске что он ругается на device_id
