### ISSUE TITLE
template_synology_diskstation_snmpv3/6.0 - SNMPv3 issues

### ISSUE THREAD

**Issue by t984447** [zabbix/community-templates#265]
Hello,

I am having major issues getting SNMPv3 to work with the mentioned template. It seems that Zabbix is having issues connecting to the Synology machine and either get _404_ or _wrong password, key or community_.

## Environment
**Synology D920+**
_DSM 7.2-64570 Update 1_

**Zabbix 6.4.1**
Running on Ubuntu Server 22.04 LTS (recently installed)

Both machines are on the same network.

## The Issue trying to use SNMPv3
When trying to setup Zabbix to use SNMPv3 with both AuthPriv however I am getting the error:
`Cannot connect to "xx.xx.1.16:161": Authentication failure (incorrect password, community or key).`

Where as the logs of Zabbix gives little help
` 16845:20230717:093358.887 SNMP agent item "synoSystem.laLoadInt.3" on host "SynologyStorage" failed: first network error, wait for 15 seconds
 16845:20230717:093413.910 SNMP agent item "synoSystem.ssCpuSystem" on host "SynologyStorage" failed: another network error, wait for 15 seconds
 16845:20230717:093428.937 SNMP agent item "synoSystem.ssCpuIdle" on host "SynologyStorage" failed: another network error, wait for 15 seconds
 16845:20230717:093443.961 temporarily disabling SNMP agent checks on host "SynologyStorage": interface unavailable
 16842:20230717:093730.165 SNMP agent item "synoSystem.ssCpuUser" on host "SynologyStorage" failed: first network error, wait for 15 seconds
 16845:20230717:093745.149 SNMP agent item "synoSystem.laLoadInt.3" on host "SynologyStorage" failed: another network error, wait for 15 seconds
 16845:20230717:093800.183 SNMP agent item "synoSystem.laLoadInt.2" on host "SynologyStorage" failed: another network error, wait for 15 seconds
`

The Synology logs dosent even mention any tries on the SNMP service.

**Do note that SNMPv2 does work.**

## Tried so far
So far Ive tried doing what is recomended in the readme;

> If you receive authentication errors, try tos set the Authentication / Privacy protocols to MD5+DES and if this works, then try to upgrade the encrypption step-by-step, changing only one attribute at a time. The choices what Zabbix can support and what is supported in a given version of DSM can be different. Find a common ground with the most strongest crypto. DES, SHA1 and MD5 are not considered cryptographically secure anymore.

That is trying each and every Auth and Pirv combination. From Auth MD5 to AuthPriv SHA512/AES265C.
between each try doing an disable/re-enable of the host just to ensure Zabbix re-tries.

This along with some restarts of the Zabbix server itself..

**Comment by Symbiot78** [comment]
I am in the same boat.

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope
