### ISSUE TITLE
Chrony scripts could use a merge.

### ISSUE THREAD

**Issue by rudolfkastl** [zabbix/community-templates#31]
There are currently 4 entries for the chrony scripts in:

https://github.com/zabbix/community-templates/tree/main/Applications/NTP

They seem to be very similar. Would be great to merge them to have less confusing duplicates.

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
If you want to update/add the new template to a repo, please, follow the instructions in the repo root (How to contribute)
