### ISSUE TITLE
Why no GPL licenses?

### ISSUE THREAD

**Issue by YoSiJo** [zabbix/community-templates#33]
In the [guidelines](https://www.zabbix.com/documentation/guidelines/en/thosts/community_templates) I found the following:

```text
Licensing

All community templates are published under the MIT license. Third-party licenses, even the compatible ones (for example, GPL v2/v3) are not accepted.
```

Furthermore, the repo is under MIT, but Zabbix itself is under GPL. I can't quite understand this step backwards in licensing.

Would it be possible to offer another repo for GPL licensed community templates?

I would love to help the community with my templates, but then also under the condition that my contribution remains free.

**Comment by oscar120584** [comment]
This decision was made by the leadership.

**Comment by YoSiJo** [comment]
I find that unfortunate but thanks for the open feedback. Would it be possible then to offer another repo for such things under [AL]GPL?
I think it is better if the Zabbix makers offer something like this than just trying to do it.
