### ISSUE TITLE
monitor 2 CISCO switches that connected in TEAMING mode

### ISSUE THREAD

**Issue by inewthinker** [zabbix/community-templates#354]
Hi all.
I am using Zabbix 6.0.2 with template "cisco IOS SNMP" in order to monitor 2 CISCO switches that connected in TEAMING mode. configure with 1 IP address.
so, I am getting in Zabbix dashboard only one switch in the display and not 2.

I have searched the web for deferent templates but no luck.
hope I have explained the issue.

BR

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope. You may to get some assistance on [Zabbix forum](https://www.zabbix.com/forum) or [Zabbix international community in Telegram](https://t.me/ZabbixTech)
