### ISSUE TITLE
Regular reports - error when generating reports

### ISSUE THREAD

**Issue by Danchik97** [zabbix/community-templates#355]
Installed zabbix-web-service on zabbix-server. All installed on the same machine.
Installed google chrome
Configured sending messages via smtp. Tested it - it works.
I make a test of regular reports and it gives an error: 
**Cannot accept incoming connection for peer: 192.168.2.71:55238.**

I don't know what the problem is. Firewall is disabled on the server

**Comment by dotneft** [comment]
please share your container config.

**Comment by Danchik97** [comment]
Cannot fetch data: chrome failed to start:

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope. You may to get some assistance on [Zabbix forum](https://www.zabbix.com/forum) or [Zabbix international community in Telegram](https://t.me/ZabbixTech)
