### ISSUE TITLE
synthetic end-user Web monitoring with ability to grab screenshots

### ISSUE THREAD

**Issue by Neelam-zanvar** [zabbix/community-templates#361]
Hi i have installed the latest version zabbix 7.0 RC1 and as seen in the post in linkedin bix-monitoringlove-comingsoon-activity-7196403529366835201-bAfO/ i wanted to know how to use the synthetic end-user Web monitoring with ability to grab screenshots feature in this version of zabbix

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope

**Comment by thestepafter** [comment]
Hello @igorbach! I see in this post (https://blog.zabbix.com/zabbix-7-0-everything-you-need-to-know/28210/) that there are screenshots to the left of the image under synthetic end-user web monitoring.

![WebMonitoringDraft2](https://github.com/user-attachments/assets/e0f4dfb4-da9c-4b29-ae28-b49882e59c30)

Is this screenshot incorrect to have the screenshots on the left? The ability to take screenshots with Zabbix is a deciding factor for me.

Thank you!
