### ISSUE TITLE
Yeastar template not correct

### ISSUE THREAD

**Issue by MrDick-11** [zabbix/community-templates#362]
I suppose you can't use name in OID. So i fixed with numbers instead of names
[yeastar_s100_trunks.yaml.txt](https://github.com/zabbix/community-templates/files/15401377/yeastar_s100_trunks.yaml.txt)

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
If you want to update/add the new template to a repo, please, follow the instructions in the repo root (How to contribute)
