### ISSUE TITLE
Non-template files from share.zabbix.com

### ISSUE THREAD

**Issue by nod0n** [zabbix/community-templates#37]
The Agent for IBM i systems, which has [a template](https://share.zabbix.com/operating-systems/ibm-i-i5-os-os-400-for-ibm-system-i-as-400/template-example-for-as-400-agent-emulator) and [the agent](https://share.zabbix.com/operating-systems/ibm-i-i5-os-os-400-for-ibm-system-i-as-400/zabbix-agent-emulator-for-as-400-platform) isn't found here on github. The template can be found here on [github](https://github.com/zabbix/community-templates/tree/main/Operating_Systems/IBM_i_(i5_OS_OS_400)_for_IBM_System_i_(AS_400)/template_example_for_as_400_agent_emulator/5.4) but the .jar file is missing.

Where should the jar-file go? If we have the template on github we also need the jar-file somewhere...

**Comment by igorbach** [comment]
The jar file is presented in tempalte page files [directory](https://github.com/zabbix/community-templates/blob/main/Operating_Systems/IBM_i_(i5_OS_OS_400)_for_IBM_System_i_(AS_400)/template_example_for_as_400_agent_emulator/5.4/files/ZabbixAgent.jar)
