### ISSUE TITLE
How to make 95 percentile graph

### ISSUE THREAD

**Issue by alemsas** [zabbix/community-templates#374]
![irancell-shiraz](https://github.com/user-attachments/assets/0bcaf46f-d058-49fe-af2a-819010905661)
I have above 95percentile on my graphs in zabbix and as you can see I have both incoming and outgoing on same side,after I lose it I make another 95 percentile here:
![image](https://github.com/user-attachments/assets/73d4d3c7-d8c5-457b-a5b8-b4f31b3dbd93)
but if I selecet bot incoming and outgoing traffic for 95 percentile on same side(right/right for example) I just get one of the percentile, and just when I select (right/left) I can see the percentile calculated, its very confuse me becuse the graph usage in this way is too close for example if my incoming traffic is 1Gbps and my outgoing is 100Mbps the graphs show somthing like this:
![image](https://github.com/user-attachments/assets/3666396b-c106-4139-a760-e644caf64eda)
1) Is it possible I have incoming and outgoing on same side?and how?
2) if above is not possible how can I have the diffrence between incoming/outgoing more real?!

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope. You may to get some assistance on [Zabbix forum](https://www.zabbix.com/forum) or [Zabbix international community in Telegram](https://t.me/ZabbixTech)
