### ISSUE TITLE
UBQT UNIFI SNMP V3 HN

### ISSUE THREAD

**Issue by stevefxp1** [zabbix/community-templates#375]
Hello all,

I am trying to import use this template with my Unifi AP environment but I am running into an issue where unifiSysName is conflicting with the system.hostname of the Linux template I am using on my self hosted Unifi controller. Do I just pull this out of the template or can you update this so it does not conflict any longer? It seems the unifiSysname is really the AP name and not the hostname coming from my Linux server?

Thanks,
Steve

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope. You may to get some assistance on [Zabbix forum](https://www.zabbix.com/forum) or [Zabbix international community in Telegram](https://t.me/ZabbixTech)
