### ISSUE TITLE
Implement monitoring with template template_agentless_storage_and_processor_statistics

### ISSUE THREAD

**Issue by 18vamberto** [zabbix/community-templates#378]
Goodnight.

I would like to implement this monitoring using your template, but the implementation steps seem to be a little confusing. I wonder if you can provide a more updated step-by-step guide.

Grateful.:

**Comment by igorbach** [comment]
Hello!
Thank you for the request
Please, follow the official template building [guidelines](https://www.zabbix.com/documentation/guidelines/en/thosts/configuration)
