### ISSUE TITLE
2 Microsoft SQL templates appear to be missing information

### ISSUE THREAD

**Issue by MatthewSteeves** [zabbix/community-templates#41]
[template_app_ms_sql_database_discovery_(lld)](https://github.com/zabbix/community-templates/tree/main/Databases/Microsoft_SQL_Server/template_app_ms_sql_database_discovery_(lld))
references key: **windowsdb.discovery**
[template_app_ms_sql_instance_discovery_(lld)](https://github.com/zabbix/community-templates/tree/main/Databases/Microsoft_SQL_Server/template_app_ms_sql_instance_discovery_(lld))
references key:  **windowssqlinstances.discovery**

These are not agent or agent2 built-in keys. Therefore there must have been additional scripts or at least user parameters that would need to be defined. **These templates should be marked as incomplete, or the additional information added.**

I tried searching for more info using:
- Google's cached page of https://share.zabbix.com/databases/microsoft-sql-server/template-app-ms-sql-database-discovery-lld
- WayBack Machine
- Author's website: https://stephenfritz.blogspot.com

**Comment by RangersMS** [comment]
Hi, I'm having the same issue right now. Tested it with Zabbix Agent 2 5.0.24 and 6.0.5.

**Comment by ablecable** [comment]
I'm also having the same issue

**Comment by chi110r** [comment]
I faced the same issue and reversed engineered the discovery for the instances discovery for our Infrastructure.

```powershell
$services = Get-Service "mssql$*"|Select-Object -ExpandProperty Name
$data = foreach ($service in $services) {
    [PSCustomObject]@{
		"{#INSTANCES}" = $service
	}
}

$data|ConvertTo-Json
```

I don't know if the instance names always match the name of the service, as they do at my company.



side note: i had to add/change the discovery filter to a marco, like this:

{$MSSQL.MULTI.INSTANCE.MATCHAES} = ".*" for match

**Comment by Georg311** [comment]
I've created a Pull Request Draft, (Only for version 6.0 and Instance)
Please @chi110r check if it is like you added.
If so i can add the other files to the PR.
And maybe afterwards we get somebody to approve it :)
