### ISSUE TITLE
Hashicorp Nomad template has gone missing

### ISSUE THREAD

**Issue by martinmcnulty** [zabbix/community-templates#42]
I can see from [Google's cache](https://webcache.googleusercontent.com/search?q=cache:v5M7vyO7ieMJ:https://share.zabbix.com/cat-app/cluster/nomad-daemon-monitoring+&cd=1&hl=en&ct=clnk&gl=uk) that there used to be a template for monitoring Nomad ("Nomad daemon monitoring"), but it doesn't appear to exist in this repo. Did it get lost in the migration?

**Comment by chrisvanmeer** [comment]
I was looking for it as well. The Consul daemon monitoring template is also missing....

**Comment by chi110r** [comment]
they where just simple proc.mem[nomad] and proc.num[nomad] items
[Consul_zabbix_template.zip](https://github.com/zabbix/community-templates/files/11554947/Consul_zabbix_template.zip)
[Nomad-zabbix-template.zip](https://github.com/zabbix/community-templates/files/11554948/Nomad-zabbix-template.zip)

**Comment by igorbach** [comment]
Hello!
Please try the official [Nomad](https://www.zabbix.com/ru/integrations/hashicorp_nomad) template
