### ISSUE TITLE
Contribute with a New Template

### ISSUE THREAD

**Issue by jonatangobbato** [zabbix/community-templates#45]
I created a new template to monitor Extreme Wireless access points, i want to share this template with the community but i dont know how to do it.

Bellow its the exported template:

`

zabbix_export:
  version: '6.0'
  date: '2022-03-01T18:11:57Z'
  groups:
    -
      uuid: 7df96b18c230490a9a0a9e2307226338
      name: Templates
    -
      uuid: 36bff6c29af64692839d077febfc7079
      name: 'Templates/Network devices'
  templates:
    -
      uuid: 13a782b8685e4781afc5c7d4f3d84094
      template: 'Template Extreme Wing AP'
      name: 'Template Extreme Wing AP'
      templates:
        -
          name: 'Template Module EtherLike-MIB SNMP'
        -
          name: 'Template Module Generic SNMP'
        -
          name: 'Template Module Interfaces SNMPv2'
      groups:
        -
          name: Templates
        -
          name: 'Templates/Network devices'
      items:
        -
          uuid: 82ace776068f4ef38a079baa2dff5e8f
          name: 'CPU Utilization'
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.388.50.1.4.2.2.2.1.0
          key: cpu.utilization
          delay: 2m
          history: 15d
          trends: 90d
          value_type: FLOAT
          units: '%'
          description: '10 times the average cpu load over the last minute (2 => .2 % cpu load)'
          preprocessing:
            -
              type: MULTIPLIER
              parameters:
                - '0.1'
          tags:
            -
              tag: Application
              value: Status
        -
          uuid: 7c1a2ca592ac45f9bf936e9337b326da
          name: 'Free Ram Memory'
          type: SNMP_AGENT
          snmp_oid: .1.3.6.1.4.1.388.50.1.4.2.2.2.3.0
          key: ram.free
          delay: 2m
          history: 15d
          trends: 90d
          value_type: FLOAT
          units: '%'
          description: '10 times the percentage of currently free RAM (687 => 68,7 % free memory)'
          preprocessing:
            -
              type: MULTIPLIER
              parameters:
                - '0.1'
          tags:
            -
              tag: Application
              value: Status
      discovery_rules:
        -
          uuid: 9e22f41724ba4b458eb3ab5f257fa3f3
          name: 'AP Discovery'
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#APNAME},.1.3.6.1.4.1.388.50.1.4.2.25.1.1.1.9]'
          key: apdiscovery
          delay: 5h
          item_prototypes:
            -
              uuid: 9f925fe64a9d4ac887e1c82489aefe6a
              name: 'Connected Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.1.1.1.4.{#SNMPINDEX}'
              key: ap.connectedclients
              delay: 5m
              history: 15d
              trends: 90d
              tags:
                -
                  tag: Application
                  value: Clients
            -
              uuid: fe064f5a147648d89d708ac77c6ed7b7
              name: 'Fault Detected'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.1.1.1.2.{#SNMPINDEX}'
              key: ap.fault.detected
              delay: 2m
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Status
            -
              uuid: 8b8ebca012a843748d27674e1f674f6e
              name: 'Last Cal Time'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.1.1.1.5.{#SNMPINDEX}'
              key: ap.lastcalltime
              delay: 5m
              trends: '0'
              value_type: CHAR
              description: 'Last Smart-RF Calibration time on the AP'
              tags:
                -
                  tag: Application
                  value: Status
            -
              uuid: 89956e24e61c48b28a67b55354edb6a5
              name: 'Number of Radios'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.1.1.1.3.{#SNMPINDEX}'
              key: ap.numradios
              delay: 3h
              history: 15d
              trends: 90d
              tags:
                -
                  tag: Application
                  value: Inventory
        -
          uuid: 5266fb642916482dab5bd86a57f01d79
          name: 'Device Discovery'
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#DEVICENAME},.1.3.6.1.4.1.388.50.1.4.2.1.1.3]'
          key: device.discovery
          delay: 5h
          item_prototypes:
            -
              uuid: ff41fd9109d94e17ae412ef943a4331d
              name: 'Device Model'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.1.1.2.{#SNMPINDEX}'
              key: device.model
              delay: 3h
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Inventory
            -
              uuid: 0e1279352dc34717a145fd414a53d277
              name: 'Online Status'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.1.1.7.{#SNMPINDEX}'
              key: device.onlinestatus
              delay: 5m
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Status
            -
              uuid: 1f44afcdd45a409993fde0d988d83d8f
              name: 'Serial Number'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.1.1.5.{#SNMPINDEX}'
              key: device.serialnumber
              delay: 3h
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Inventory
            -
              uuid: 16f97762026f4dd7bbbe0946d78ef30d
              name: 'Device Version'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.1.1.4.{#SNMPINDEX}'
              key: device.version
              delay: 3h
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Inventory
        -
          uuid: 94e85699c0a94b62a72261ccaca60989
          name: 'Radios Discovery'
          type: SNMP_AGENT
          snmp_oid: 'discovery[{#RADIONAME},.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.3,{#RADIOALIAS},.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.5]'
          key: radios.discovery
          delay: 5h
          item_prototypes:
            -
              uuid: ba4cbe114afc4811aa415c2b1f87c440
              name: '{#RADIONAME}:{#RADIOALIAS} 11a Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.26.{#SNMPINDEX}'
              key: 'radio.11aclients.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: 'Number of 11a clients'
              tags:
                -
                  tag: Application
                  value: Clients
                -
                  tag: Application
                  value: Radios
            -
              uuid: 0ea1634bc1c04238b79ca124c37b477c
              name: '{#RADIONAME}:{#RADIOALIAS} 11an Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.27.{#SNMPINDEX}'
              key: 'radio.11anclients.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: 'Number of 11an clients'
              tags:
                -
                  tag: Application
                  value: Clients
                -
                  tag: Application
                  value: Radios
            -
              uuid: 09c3a2d134644e8da7eddc4f73e45cac
              name: '{#RADIONAME}:{#RADIOALIAS} 11b Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.23.{#SNMPINDEX}'
              key: 'radio.11bclients.[{#RADIONAME}]'
              delay: 5m
              description: 'Number of 11b connected clients'
              tags:
                -
                  tag: Application
                  value: Clients
                -
                  tag: Application
                  value: Radios
            -
              uuid: c39f74e76b0a45e096da8cd3237e8e06
              name: '{#RADIONAME}:{#RADIOALIAS} 11bg Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.24.{#SNMPINDEX}'
              key: 'radio.11bgclients.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: 'Number of 11bg clients'
              tags:
                -
                  tag: Application
                  value: Clients
                -
                  tag: Application
                  value: Radios
            -
              uuid: 38090621897946be8011eaabbd813d49
              name: '{#RADIONAME}:{#RADIOALIAS} 11bgn Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.25.{#SNMPINDEX}'
              key: 'radio.11bgnclients.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: 'Number of 11bgn clients'
              tags:
                -
                  tag: Application
                  value: Clients
                -
                  tag: Application
                  value: Radios
            -
              uuid: b8929fb8e366410fbad2ee96c9de69d8
              name: '{#RADIONAME}:{#RADIOALIAS} Clients'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.15.{#SNMPINDEX}'
              key: 'radio.clients.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: 'Connected clients'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 7ebebf5bef9e4e17951b78f231c035d7
              name: '{#RADIONAME}:{#RADIOALIAS} Config Channel'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.11.{#SNMPINDEX}'
              key: 'radio.configchannel.[{#RADIONAME}]'
              delay: 10m
              history: 15d
              trends: '0'
              value_type: CHAR
              description: |
                Configured Channel
                smt =  Smart RF
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 6db62783223046e0b41b2c11de6c9565
              name: '{#RADIONAME}:{#RADIOALIAS} Config Power'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.13.{#SNMPINDEX}'
              key: 'radio.configpower.[{#RADIONAME}]'
              delay: 10m
              history: 15d
              trends: '0'
              value_type: CHAR
              description: |
                Configured Power
                smt = Smart RF
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 163b6c739e0f466fbb413da15a19efb0
              name: '{#RADIONAME}:{#RADIOALIAS} Current Channel'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.10.{#SNMPINDEX}'
              key: 'radio.curchannel.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: '0'
              value_type: CHAR
              description: 'Current utilized channel'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: f93d8e94669743a3b63ed63483d2f4d9
              name: '{#RADIONAME}:{#RADIOALIAS} Current power'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.12.{#SNMPINDEX}'
              key: 'radio.curpower.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 30d
              units: dBm
              description: 'Current power level'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: d510d0ea633d481a99085b886537ff6e
              name: '{#RADIONAME}:{#RADIOALIAS} Error Rate'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.20.{#SNMPINDEX}'
              key: 'radio.errorrate.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: '%'
              description: 'Ratio of errors to rx-packets in percentage'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 07620305a6414581a630aaa585d91e74
              name: '{#RADIONAME}:{#RADIOALIAS} Max User Rate'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.14.{#SNMPINDEX}'
              key: 'radio.maxuserrate.[{#RADIONAME}]'
              delay: 1h
              history: 7d
              trends: '0'
              units: kbps
              description: 'Theoretic maximum user-level data rate'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: e96f42280af844de961bde985dd26957
              name: '{#RADIONAME}:{#RADIOALIAS} Noise'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.16.{#SNMPINDEX}'
              key: 'radio.noise.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              units: dbm
              description: 'Noise level in units of dbm'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 349a9f0ccf35422c8bb38278d1c18bab
              name: '{#RADIONAME}:{#RADIOALIAS} Radio Protocol'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.16.{#SNMPINDEX}'
              key: 'radio.protocol.[{#RADIONAME}]'
              delay: 1h
              history: 7d
              trends: '0'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 6333954998a2473481a797ed86c7a031
              name: '{#RADIONAME}:{#RADIOALIAS} Quality Index'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.21.{#SNMPINDEX}'
              key: 'radio.quality.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: '%'
              description: |
                RF quality Index
                				Measure the quality of the medium in percentage. It is a
                				function of average retries and error rate. Its range is from
                				0-100. Typically:
                				  -1: no data available ( e.g. radio is not in wlan operation
                				                          mode )
                				  0-20: very poor quality
                				  20-40: poor quality
                				  40-60: average quality
                				  60-100: good quality
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: f7fb96538f7c4425bd7a213d410e2d36
              name: '{#RADIONAME}:{#RADIOALIAS} Rx Bps'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.14.{#SNMPINDEX}'
              key: 'radio.rxbps.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: bps
              description: 'User data receive rate'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 7f7cd09342c04b8ba12292893478d552
              name: '{#RADIONAME}:{#RADIOALIAS} Rx Bytes'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.7.{#SNMPINDEX}'
              key: 'radio.rxbytes.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              units: B
              description: 'Number of data bytes received from clients to radio'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: a701ca7f1d2245e881a17f7495eccd81
              name: '{#RADIONAME}:{#RADIOALIAS} Rx Errors'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.11.{#SNMPINDEX}'
              key: 'radio.rxerrors.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              description: 'Number of packets of data received with errors'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: fd9c5f41b838449b8928af898c123083
              name: '{#RADIONAME}:{#RADIOALIAS} Rx Rate'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.19.{#SNMPINDEX}'
              key: 'radio.rxrate.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: Mbps
              description: 'The effective phy-layer receive rate'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 55d5931affbd4e689ea65d17405cc12d
              name: '{#RADIONAME}:{#RADIOALIAS} Signal'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.15.{#SNMPINDEX}'
              key: 'radio.signal.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              units: dbm
              description: 'Signal strength in units of dbm'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 2a5396b2105a4b728faf2841e409c040
              name: '{#RADIONAME}:{#RADIOALIAS} Signal to Noise'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.17.{#SNMPINDEX}'
              key: 'radio.snr.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: db
              description: 'Signal to noise ratio in units of db'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: d2c7e8b4f9cd49789e699da6161acec3
              name: '{#RADIONAME}:{#RADIOALIAS} Status'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.9.{#SNMPINDEX}'
              key: 'radio.status.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: '0'
              value_type: CHAR
              description: 'Radio state'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 4843f9188322421c97117a41210e0eab
              name: '{#RADIONAME}:{#RADIOALIAS} Traffic Utilization Index'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.12.{#SNMPINDEX}'
              key: 'radio.tindex.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              description: |
                Traffic Utilization Index
                				Measures the efficiency the medium under consideration
                				is used. It is the percentage of the current data throughput
                				over the theoretical data rate limit, which is derived
                				the current maximum physical rate configured over the medium
                				based on past empirical data. This index could assist end user
                				in site planning and expansion. The numerical value might be
                				further classified as:
                				  -1: no data available ( e.g. radio is not in wlan operation
                				                          mode )
                				  0-20 : very low utilization
                				  20-40: low utilization
                				  40-60: moderate utilization
                				  60 and above: high utilization
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: afed6ff5f7f44bed9e8d517614fe5383
              name: '{#RADIONAME}:{#RADIOALIAS} Tx Bps'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.13.{#SNMPINDEX}'
              key: 'radio.txbps.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: kbps
              description: 'User data transmit rate'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 23f180db0e934d94baf5c2085172f89b
              name: '{#RADIONAME}:{#RADIOALIAS} Tx Bytes'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.6.{#SNMPINDEX}'
              key: 'radio.txbytes.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              units: B
              description: 'Number of data bytes transmitted from radio to clients'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 263dddd2d6494de7802f9d29049323f0
              name: '{#RADIONAME}:{#RADIOALIAS} Tx Dropped'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.10.{#SNMPINDEX}'
              key: 'radio.txdropped.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              value_type: FLOAT
              description: 'Number of packets of data dropped on transmission'
              tags:
                -
                  tag: Application
                  value: Radios
            -
              uuid: 0b431df6bcb5405d99245541b8b47a0c
              name: '{#RADIONAME}:{#RADIOALIAS} Tx Rate'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.10.1.1.18.{#SNMPINDEX}'
              key: 'radio.txrate.[{#RADIONAME}]'
              delay: 5m
              history: 15d
              trends: 90d
              units: Mbps
              description: 'The effective phy-layer transmit rate'
            -
              uuid: 37f8a4a45276410b852ed68b4bc0401c
              name: '{#RADIONAME}:{#RADIOALIAS} Radio Type'
              type: SNMP_AGENT
              snmp_oid: '.1.3.6.1.4.1.388.50.1.4.2.25.9.1.1.5.{#SNMPINDEX}'
              key: 'radio.type.[{#RADIONAME}]'
              delay: 1h
              history: 15d
              trends: '0'
              value_type: CHAR
              tags:
                -
                  tag: Application
                  value: Radios
      macros:
        -
          macro: '{$IF_ERRORS_WARN}'
          value: '1000'
`

**Comment by NexonSU** [comment]
@jonatangobbato can you please share this template as file?
You posted yaml template without identation.

**Comment by NexonSU** [comment]
Updated version of Template Extreme Wing AP for 6.4
[Template Extreme Wing AP.zip](https://github.com/zabbix/community-templates/files/11333083/Template.Extreme.Wing.AP.zip)

**Comment by jonatangobbato** [comment]
Hello @NexonSU,

i exported the template that i'm using now with some update for compare.
[Extreme_Template.zip](https://github.com/zabbix/community-templates/files/11335415/Extreme_Template.zip)

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
If you want to update/add the new template to a repo, please, follow the instructions in the repo root (How to contribute)
