### ISSUE TITLE
404 on ssl LLD template, please include scripts

### ISSUE THREAD

**Issue by rbicelli** [zabbix/community-templates#49]
Hello,
SSL LLD template (https://github.com/zabbix/community-templates/tree/main/Applications/Web-servers/template_domain_registration_expiration_and_ssl_certificates_check_lld) reference to another template supposed to containing scripts, which points to a 404 page. Without scripts templates is useless, so is it possible to include them?
Thanks

**Comment by oscar120584** [comment]
Yes, we are working on it. For this template the solution is here https://github.com/zabbix/community-templates/blob/main/Applications/Web-servers/template_domain_registration_expiration_and_ssl_certificates_check_lld/6.0/files/additional_info.txt
