### ISSUE TITLE
template_synology_diskstation wrong volume size calculated

### ISSUE THREAD

**Issue by johnhoogeveen** [zabbix/community-templates#55]
The disksize is calculated with a fixed multiplier of 4096, however, the value can be also different as it is with my unit.
Checking the value for  hrStorageAllocationUnits with mibbrowser shows 16384 instead of 4096.
Another volume on the unit  has 4096 for hrStorageAllocationUnits.
My suggestion would be to calculate with the value of hrStorageAllocationUnits.

Below a filtered view of the snmp information.

"hrStorageIndex","hrStorageType","hrStorageDescr","**hrStorageAllocationUnits**","hrStorageSize","hrStorageUsed","hrStorageAllocationFailures","Index Value"
"55",".1.3.6.1.2.1.25.2.1.4","/volume1","**16384**","1170658963","864524997",""," 55"
"56",".1.3.6.1.2.1.25.2.1.4","/volumeUSB2/usbshare","4096","360501858","314950992",""," 56"
"61",".1.3.6.1.2.1.25.2.1.4","/volumeUSB1/usbshare","4096","720787053","382743615",""," 61"
"63",".1.3.6.1.2.1.25.2.1.4","/volume2","**4096**","54861497","1497091",""," 63"

**Comment by k008** [comment]
`return (parseInt(value) * parseInt("{#IFUNIT}"));`

![изображение](https://user-images.githubusercontent.com/8766589/177171771-81099ee5-d5b1-4af3-a04a-fd0a0b814fd6.png)

**Comment by johnhoogeveen** [comment]
I am not really sure how this would fix my challenge, when I change it in the template it would be applied to all volumes monitored (I guess)
But one unit has 2 different allocation unit values and then volume2 would be displayed incorrect.

**Comment by k008** [comment]
Обратите внимание на множитель **{#IFUNIT}**  в скрипте, это макрос из snmp под разные разделы он свой. Множитель 4096 удалите у себя

**Comment by johnhoogeveen** [comment]
Sorry for taking ages to respond, this java script indeed solves the issue, all values are shown correctly
