### ISSUE TITLE
Template 'macOS Content Cache' does not create graphs. 

### ISSUE THREAD

**Issue by Karo-X** [zabbix/community-templates#59]
The RemoteCommands are executed, but the values received are not transferred to the graphic.

The output according to the test: 

`{"name":"status","result":{"Activated":true,"Active":true,"ActualCacheUsed":1781398204,"CacheDetails":{"iCloud":150581984,"iOS Software":1758456112},"CacheFree":19506686976,"CacheLimit":994000000000,"CacheStatus":"OK","CacheUsed":1909038096,"MaxCachePressureLast1Hour":0,"Parents":[],"Peers":[],"PersonalCacheFree":19506686976,"PersonalCacheLimit":994000000000,"PersonalCacheUsed":150581984,"Port":52923,"PrivateAddresses":["192.168.178.204"],"PublicAddress":"89.1.213.19","RegistrationStatus":1,"RestrictedMedia":false,"ServerGUID":"ED91D0ED-04B5-4192-B972-87099F46079A","StartupStatus":"OK","TetheratorStatus":1,"TotalBytesAreSince":"2022-03-18 13:09:06 +0000","TotalBytesDropped":0,"TotalBytesImported":5667338,"TotalBytesReturnedToChildren":0,"TotalBytesReturnedToClients":1775744901,"TotalBytesReturnedToPeers":0,"TotalBytesStoredFromOrigin":1775730866,"TotalBytesStoredFromParents":0,"TotalBytesStoredFromPeers":0}}`

**Comment by igorbach** [comment]
Hello!
Thank you for a request!
Unfortunately, your question is out of scope
